name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:

  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint
        continue-on-error: true

      - name: Generate ESLint HTML Report
        if: always()
        run: npm run lint:report
        continue-on-error: true

      - name: Upload ESLint Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: eslint-report
          path: eslint-reports/
          retention-days: 30


  test_registration:

    # Job deaktiviert with if : false

    # needs: lint 
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
       node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install

    - name: npm run test:staging:tag "@STAGING @Registration"
      # Führt alle Teste in der staging umgebung aus mit den Tags @STAGING und @Registration
      # staging wird automatisch mit headless=true ausgeführt
      # Diese Tags müssen in dem Testfile vorhanden sein
      # run: npm run test:staging:tag "@STAGING @Registration"
      run: npm run test:staging:tc:headed "@TC-XX000"

    - name: Generate Allure Report
      if: ${{ !cancelled() }}
      run: |
        npx allure generate allure-results -o allure-report --clean
      continue-on-error: true

    - name: Upload Playwright Report
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: Upload Allure Results (Raw Data)
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: allure-results/
        retention-days: 30

    - name: Upload Allure Report (HTML)
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report/
        retention-days: 30


        